/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ventana.java
 *
 * Created on 9/05/2013, 04:22:01 PM
 */

package x;

/**
 *
 * @author Administrador
 */

import com.sun.j3d.utils.universe.SimpleUniverse;
import java.awt.Color;
import java.awt.GraphicsConfiguration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Canvas3D;
import javax.media.j3d.Locale;
import javax.media.j3d.Transform3D;
import javax.media.j3d.TransformGroup;
import javax.swing.JPanel;
import javax.vecmath.Vector3d;
public class Ventana extends javax.swing.JFrame implements Runnable{

    /** Creates new form Ventana */
     Thread hilo = new Thread(this);
    Figura3D figura = new Figura3D();
    float a = -1.5f;
    float b = 0.0f;
    float c = 0.0f;
            
    public Ventana() {
        initComponents();
        JPanel panel1=new JPanel();
        panel1.setBounds(0,0,600,600);
        panel1.setBackground(Color.black);
        this.add(panel1);
        this.setBounds(10, 0, 800, 600);

        GraphicsConfiguration config=SimpleUniverse.getPreferredConfiguration();
        Canvas3D canvas3D=new Canvas3D(config);
        canvas3D.setBounds(0, 0, 600, 600);
        panel1.add(canvas3D);

        BranchGroup scene;
            scene= createSceneGraph();
       scene.compile();
       SimpleUniverse su=new SimpleUniverse(canvas3D);
       su.getViewingPlatform().setNominalViewingTransform();
       su.addBranchGraph(scene);

       hilo.start();
    }

    public BranchGroup createSceneGraph(){
        return figura.rootGroup;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("detener");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("adelante");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("izquierda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("derecha");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Atras");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(460, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(24, 24, 24)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(hilo.isAlive()==true)
        {
        hilo.stop();
        }
        else{
            hilo = new Thread(this);
            hilo.start();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Transform3D transTodo=new Transform3D();
         Transform3D transTodo2=new Transform3D();
         a += 0.1;
         b -= 0.005;
         transTodo.rotY(Math.PI/180*90);
        
        transTodo2.setTranslation(new Vector3d(a,b,c));
        transTodo.mul(transTodo2);
        
        
        
        figura.objSpin.setTransform(transTodo);

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        Transform3D transTodo=new Transform3D();
         Transform3D transTodo2=new Transform3D();
          Transform3D transTodo3=new Transform3D();
          
         transTodo.rotY(Math.PI/180*90);
         transTodo3.rotY(Math.PI/180*30);
        
         c -= 0.5;
        transTodo2.setTranslation(new Vector3d(a,b,c));
        transTodo2.mul(transTodo3);
        transTodo.mul(transTodo2);
        
        
        
        figura.objSpin.setTransform(transTodo);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        Transform3D transTodo=new Transform3D();
         Transform3D transTodo2=new Transform3D();
          Transform3D transTodo3=new Transform3D();
          
         transTodo.rotY(Math.PI/180*90);
         transTodo3.rotY(Math.PI/180*-30);
        c +=0.05;
        transTodo2.setTranslation(new Vector3d(a,b,c));
        transTodo2.mul(transTodo3);
        transTodo.mul(transTodo2);
        
         figura.objSpin.setTransform(transTodo);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Transform3D transTodo=new Transform3D();
         Transform3D transTodo2=new Transform3D();
         a -= 0.1;
         b += 0.005;
         transTodo.rotY(Math.PI/180*90);
        
        transTodo2.setTranslation(new Vector3d(a,b,c));
        transTodo.mul(transTodo2);
        
        
        
        figura.objSpin.setTransform(transTodo);
    }//GEN-LAST:event_jButton6ActionPerformed

    public void moverLlantas()
    {
        Transform3D temp = new Transform3D();
           Transform3D temp2 = new Transform3D();
           Transform3D tempDelta = new Transform3D();
           Transform3D tempDelta1 = new Transform3D();
           Transform3D tempDelta2 = new Transform3D();
           Transform3D tempDelta3 = new Transform3D();
           Transform3D temp3 = new Transform3D();
           Transform3D temp4 = new Transform3D();
           Transform3D tempDelta4 = new Transform3D();
           Transform3D tempDelta41 = new Transform3D();
           Transform3D tempDelta5 = new Transform3D();
           Transform3D tempDelta51 = new Transform3D();

           figura.rotarLlanta1.getTransform(temp);
	   tempDelta.rotY(0.3);
           float x=(float) 0.02;
           tempDelta1.setTranslation(new Vector3d(0.0f,0.0f,x));
	   tempDelta1.mul(tempDelta);
           temp.mul(tempDelta1);
           figura.rotarLlanta1.setTransform(temp);

           figura.rotarLlanta2.getTransform(temp2);
	   tempDelta2.rotY(0.3);
           tempDelta3.setTranslation(new Vector3d(0.0f,0.0f,x));
	   tempDelta3.mul(tempDelta2);
           temp2.mul(tempDelta3);

           figura.rotarLlanta2.setTransform(temp2);

           figura.rotarLlanta3.getTransform(temp3);
	   tempDelta4.rotY(0.3);
           //
           tempDelta41.setTranslation(new Vector3d(0.0f,0.0f,x));
	   tempDelta41.mul(tempDelta4);
           temp3.mul(tempDelta41);
           figura.rotarLlanta3.setTransform(temp3);

           figura.rotarLlanta4.getTransform(temp4);
	   tempDelta5.rotY(0.3);

           tempDelta51.setTranslation(new Vector3d(0.0f,0.0f,x));
	   tempDelta51.mul(tempDelta5);
           temp4.mul(tempDelta51);
           figura.rotarLlanta4.setTransform(temp4);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration//GEN-END:variables

    public void run() {

        while(true)
        {
            moverLlantas();
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}
